server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-services
          uri: lb://user-service
          predicates:
            - Path=/api/**
        - id: user-services
            uri: lb://bulletin-service
            predicates:
              - Path=/api/**