server:
  port: 8002
spring:
  application:
    name: bulletin-service
  datasource:
    url: 'jdbc:mysql://localhost:3306/news_dev'
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost
