server:
  port: 8002
spring:
  application:
    name: bulletin-service
  datasource:
    url: 'jdbc:mysql://localhost:3306/news_dev'
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update