server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: user-service
  datasource:
    url: 'jdbc:mysql://localhost:3306/auth_dev'
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
jwt:
  secret: techgeeknext
app:
  jwt-secret: JWTSecretKey
  jwt-expiration-millisecond: '604800000'
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}